# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

production:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: hospital_production
  pool: 5
  username: ivan_pg
  password: 123456
